db.url=jdbc:mysql://localhost:3306/sales
db.username=your_mysql_username
db.password=your_mysql_password
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=your-email@gmail.com
mail.smtp.password=your_gmail_app_password
mail.recipient=recipient@example.com
mail.subject=Weekly Sales Insight Report
mail.body=Hello,\n\nPlease find attached the weekly sales insight report.\n\nBest regards,\nSales Team
mail.attachment.path=/path/to/weekly_sales_report.pdf


gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=your_gemini_api_key

gemini.api.model=gemini-1.5-flash
gemini.api.temperature=0.5  
gemini.api.maxOutputTokens=1000
