db.url=jdbc:mysql://localhost:3306/sales
db.username=Your_username
db.password=Your_DB_password
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=Your_mail_Id
mail.smtp.password=Your_password
mail.recipient=recipient_mail_Id
mail.subject=Weekly Sales Insight Report
mail.body=Hello,\n\nPlease find attached the weekly sales insight report.\n\nBest regards,\nSales Team
mail.attachment.path=/path/to/weekly_sales_report.pdf


gemini.api.url=Your_api_url
gemini.api.key=Your_api_key

gemini.api.model=gemini-1.5-flash
gemini.api.temperature=0.5  
gemini.api.maxOutputTokens=1000